version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing base packages"
      - npm install

  build:
    commands:
      - npm run build

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist
